default_model: "haiku"
auto_sampling: true

mcp:
  servers:
    Demo: # demo/server/server.py
      transport: "sse"
      url: "did:webvh:QmYGANngq3HzToTDxaviEpHT9791WEKKU8FnkYnzCzsJ6Z:did.teaspoon.world:endpoint:DemoTmcpSseServer-8979ca15-f794-45fc-881a-588e01b15ab0" # put your server's DID here
      roots:
        - uri: "file://some-file.txt"
          name: Some File

anthropic:
