default_model: "haiku"
auto_sampling: true

mcp:
  servers:
    Demo: # demo/server/server.py
      transport: "http"
      url: "did:webvh:QmcbCiD4YPad7Vkyo9waM8E7bduUaw6XLoEJ1XKbGPZikE:did.teaspoon.world:endpoint:tmcp-8ff3f79e-495f-43e2-b906-35c886afb41b" # put your server's DID here
      roots:
        - uri: "file://some-file.txt"
          name: Some File

    DuckDuckGo: #demo/server-duckduckgo $ uv run duckduckgo-mcp-server
      transport: "http"
      url: "did:webvh:QmQetHAFkPCJh6qNYvskjMsRE2iW9f6sZBrXqftEDvYFAn:did.teaspoon.world:endpoint:tmcp-6e6054fe-2cd2-4f64-bb98-c5a36c31951e"

    Gmail: # demo/server-gmail/gmail_server.py
      transport: "http"
      url: "did:webvh:QmVCKzXb199BgzvL7eDFz8BATVJZfVcVH7G5AQaaYj7PAj:did.teaspoon.world:endpoint:tmcp-99140102-b43d-4a27-8cfb-3044dc9539f6"

    GitHub: # demo/server-github-demo/server.py
      transport: "http"
      url: "did:webvh:QmUYzK2tgVEKhhiH2Nch83LfmKJqFCwuBTMLZtZh5Xtrko:did.teaspoon.world:endpoint:tmcp-ba2c1fc8-ef24-41c1-a8f6-9838b34de4da"
