default_model: "haiku"
auto_sampling: true

mcp:
  servers:
    Demo: # demo/server/server.py
      transport: "sse"
      url: "did:webvh:QmUiP7DdmPAdpB2EwZHjuECj1VszcXz9hB6sZo9GDfaKv4:did.teaspoon.world:endpoint:DemoTmcpSseServer-c8122659-e9db-4ec4-a487-b6fa5b394722" # put your server's DID here

anthropic:
